import type { AppState } from "@/shared/model/app-state";
import * as seeds from "./seed-project-lists";
const stamp = "2026-08-11T08:00:00.000Z";
export function createSeedState(): AppState {
  return {
    schemaVersion: 1,
    revision: 1,
    updatedAt: stamp,
    profile: { name: "Me", avatarDataUrl: "" },
    messages: [],
    cycles: [
      {
        id: "cycle_aug",
        name: "八月成长周期",
        startDate: "2026-08-01",
        endDate: "2026-08-31",
        cadence: "month",
        status: "active",
        review: "",
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    goals: [
      {
        id: "goal_research",
        cycleId: "cycle_aug",
        title: "完成研究原型",
        target: 40,
        current: 26,
        unit: "小时",
        dueDate: "2026-08-31",
        priority: "high",
        status: "active",
        createdAt: stamp,
        updatedAt: stamp,
      },
      {
        id: "goal_read",
        cycleId: "cycle_aug",
        title: "深度阅读文献",
        target: 8,
        current: 3,
        unit: "篇",
        dueDate: "2026-08-31",
        priority: "medium",
        status: "active",
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    focus: [
      {
        id: "session_1",
        cycleId: "cycle_aug",
        goalId: "goal_research",
        projectId: "project_arch",
        taskId: "task_scope",
        title: "架构需求梳理",
        startedAt: "2026-08-10T01:00:00.000Z",
        endedAt: "2026-08-10T02:30:00.000Z",
        duration: 90,
        focusOn: "task_scope",
        minutes: 90,
        effective: true,
        focus: 4,
        output: "完成需求边界",
        note: "",
        createdAt: stamp,
        updatedAt: stamp,
      },
      {
        id: "session_2",
        cycleId: "cycle_aug",
        goalId: "goal_read",
        title: "阅读多模态架构论文",
        startedAt: "2026-08-09T06:00:00.000Z",
        endedAt: "2026-08-09T07:00:00.000Z",
        duration: 60,
        focusOn: "",
        minutes: 60,
        effective: true,
        focus: 5,
        output: "形成一条灵感",
        note: "",
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    events: [
      {
        id: "event_1",
        cycleId: "cycle_aug",
        projectId: "project_arch",
        type: "success",
        phenomenon: "提前完成需求边界",
        reason: "先定义验收场景",
        impact: "减少了返工",
        evidence: "项目日志 #1",
        action: "后续项目继续先写验收标准",
        category: "method",
        confirmed: true,
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    libraryLists: [
      {
        id: "library_default",
        name: "Default List",
        note: "All imported literature",
        tags: [],
        color: "#18181b",
        system: "default",
        createdAt: stamp,
        updatedAt: stamp,
      },
      {
        id: "library_recent",
        name: "Recently Added",
        note: "Literature ordered by import time",
        tags: [],
        color: "#2563eb",
        system: "recent",
        createdAt: stamp,
        updatedAt: stamp,
      },
      {
        id: "library_marked",
        name: "Marked",
        note: "All marked literature",
        tags: [],
        color: "#ef4444",
        system: "marked",
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    projectLists: seeds.seedProjects(stamp),
    activityLists: seeds.seedActivityLists(stamp),
    ideaLists: seeds.seedIdeas(stamp),
    pointLists: seeds.seedPointLists(stamp),
    points: [],
    sources: [
      {
        id: "source_multi",
        title: "Multimodal Architecture Notes",
        authors: "Research group",
        year: "2026",
        origin: "Local note",
        citation: "Research group. Multimodal Architecture Notes. 2026.",
        category: "manual",
        fileName: "multimodal.md",
        fileToken: "",
        filePath: "",
        markdownToken: "",
        markdownPath: "",
        fileType: "markdown",
        content:
          "# Multimodal architecture\n\nA modular system can align signals while keeping domain encoders independent.",
        summary:
          "研究问题：如何保持模态独立性的同时完成对齐。\n方法：模块化编码器。\n局限：缺少长期运行数据。",
        guide:
          "AI 草稿 · 来源：全文\n该方法强调模块边界与共享表示之间的平衡。内容待用户核实。",
        tags: ["架构", "多模态"],
        listIds: ["library_default"],
        favorite: true,
        rating: 4,
        publicationDate: "2026",
        readingStatus: "read",
        readingStartedAt: stamp,
        readingCompletedAt: stamp,
        studyDurationMinutes: 60,
        readingReview: {
          type: "method",
          problem: "如何保持模态独立性的同时完成对齐？",
          approach: "使用模块化编码器。",
          result: "形成低耦合的多模态架构。",
          limitation: "缺少长期运行数据。",
          inspiration: "模块边界可降低系统耦合。",
          structure: "问题、方法、结果与讨论。",
        },
        conversionStatus: "ready",
        conversionMessage: "Page 1 mapped",
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    annotations: [
      {
        id: "annotation_1",
        sourceId: "source_multi",
        location: "Page 1",
        quote: "keeping domain encoders independent",
        kind: "positive",
        reason: "适合作为低耦合架构正例",
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    ideas: [seeds.seedIdea(stamp)],
    projects: [
      {
        id: "project_arch",
        name: "自适应研究架构",
        purpose: "验证模块化知识闭环",
        expected: "可运行原型与博文",
        startDate: "2026-08-05",
        endDate: "2026-08-28",
        status: "active",
        goalId: "goal_research",
        ideaIds: ["idea_decentral"],
        listIds: [],
        tags: ["架构"],
        score: 82,
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    activities: [
      {
        id: "task_scope",
        projectId: "project_arch",
        title: "定义原型范围",
        description: "明确原型覆盖的核心场景和边界。",
        startDate: "2026-08-09T22:00",
        dueDate: "2026-08-10",
        priority: "high",
        status: "done",
        estimatedMinutes: 120,
        actualMinutes: 90,
        milestone: true,
        expectedOutput: "原型范围说明",
        ...{ impact: 4, goal: 4, risk: 4, value: 4, delayLoss: 3, dependencyIds: [], complexity: 3, uncertainty: 3 },
        importance: 16,
        recurrence: null,
        activityType: "task",
        completedAt: stamp,
        createdAt: stamp,
        updatedAt: stamp,
      },
      {
        id: "task_test",
        projectId: "project_arch",
        title: "验证核心闭环",
        description: "验证从文献到项目的核心链路。",
        startDate: "2026-08-17T20:00",
        dueDate: "2026-08-18",
        priority: "high",
        status: "doing",
        estimatedMinutes: 240,
        actualMinutes: 60,
        milestone: false,
        expectedOutput: "验证记录",
        ...{ impact: 4, goal: 4, risk: 4, value: 4, delayLoss: 3, dependencyIds: [], complexity: 3, uncertainty: 3 },
        importance: 16,
        recurrence: null,
        activityType: "task",
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    logs: [
      {
        id: "log_1",
        projectId: "project_arch",
        period: "day",
        filePath: "project/project_arch/logs/log_1.md",
        taskId: "task_scope",
        type: "decision",
        content: "采用本地优先并保留可替换适配器。",
        nextStep: "实现端到端原型",
        sourceIds: ["source_multi"],
        ideaIds: ["idea_decentral"],
        tags: ["架构"],
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    attachments: [],
    artifacts: [
      {
        id: "artifact_1",
        title: "从信息到成果：个人研究闭环",
        type: "blog",
        status: "draft",
        content:
          "# 从信息到成果\n\n## 问题\n知识管理为何常常停留在收藏？\n\n## 方法\n通过可追溯的五阶段闭环把输入连接到成果。\n\n> 待核实：长期使用的效率提升幅度。",
        projectIds: ["project_arch"],
        sourceIds: ["source_multi"],
        ideaIds: ["idea_decentral"],
        materials: [
          "项目：自适应研究架构",
          "文献：Multimodal Architecture Notes",
        ],
        tags: ["知识管理"],
        channel: "",
        externalUrl: "",
        feedback: "",
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    relations: [],
    aiJobs: [],
  };
}
